[tool.poetry]
name = "product-service"
version = "0.1.0"
description = ""
authors = ["Umar Hayyat <umarhayyat71.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
